//! Core types for JOLT-Atlas zkML proofs

use serde::{Deserialize, Serialize};

/// Model commitment - cryptographic binding to a specific model version
///
/// Generated from model weights and architecture, this commitment ensures
/// that proofs can only be generated by the registered model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelCommitment {
    /// Keccak256 hash of model weights
    pub weights_hash: [u8; 32],

    /// Keccak256 hash of model architecture specification
    pub architecture_hash: [u8; 32],

    /// Combined commitment: keccak256(weights_hash || architecture_hash)
    pub commitment: [u8; 32],

    /// Model version identifier
    pub version: String,

    /// Unix timestamp when commitment was generated
    pub created_at: u64,
}

impl ModelCommitment {
    /// Create a new model commitment from components
    pub fn new(
        weights_hash: [u8; 32],
        architecture_hash: [u8; 32],
        commitment: [u8; 32],
        version: String,
    ) -> Self {
        Self {
            weights_hash,
            architecture_hash,
            commitment,
            version,
            created_at: current_timestamp(),
        }
    }

    /// Get hex-encoded commitment string
    pub fn commitment_hex(&self) -> String {
        hex::encode(self.commitment)
    }

    /// Get hex-encoded weights hash
    pub fn weights_hash_hex(&self) -> String {
        hex::encode(self.weights_hash)
    }

    /// Get hex-encoded architecture hash
    pub fn architecture_hash_hex(&self) -> String {
        hex::encode(self.architecture_hash)
    }
}

/// Input commitment - privacy-preserving hash of transaction context
///
/// This allows verification without revealing the actual input data.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InputCommitment {
    /// Keccak256 hash of input data
    pub hash: [u8; 32],

    /// Input schema version for compatibility
    pub schema_version: u32,
}

impl InputCommitment {
    /// Create input commitment from raw bytes
    pub fn from_bytes(data: &[u8]) -> Self {
        use sha3::{Digest, Keccak256};

        let mut hasher = Keccak256::new();
        hasher.update(data);
        let hash: [u8; 32] = hasher.finalize().into();

        Self {
            hash,
            schema_version: 1,
        }
    }

    /// Get hex-encoded hash
    pub fn hash_hex(&self) -> String {
        hex::encode(self.hash)
    }
}

/// Output commitment - hash of model decision
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutputCommitment {
    /// Keccak256 hash of output data
    pub hash: [u8; 32],

    /// Type of decision made
    pub decision_type: DecisionType,
}

impl OutputCommitment {
    /// Create output commitment from inference result
    pub fn from_inference_result(output: &InferenceOutput) -> Self {
        use sha3::{Digest, Keccak256};

        let output_bytes = serde_json::to_vec(output).unwrap_or_default();
        let mut hasher = Keccak256::new();
        hasher.update(&output_bytes);
        let hash: [u8; 32] = hasher.finalize().into();

        Self {
            hash,
            decision_type: output.decision_type.clone(),
        }
    }

    /// Get hex-encoded hash
    pub fn hash_hex(&self) -> String {
        hex::encode(self.hash)
    }
}

/// Decision types for agent transactions
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DecisionType {
    /// Transaction approved
    Approve,
    /// Transaction denied
    Deny,
    /// Escalate to human review
    Escalate,
    /// Defer decision
    Defer,
}

impl Default for DecisionType {
    fn default() -> Self {
        Self::Defer
    }
}

/// Result of model inference
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferenceOutput {
    /// The decision type
    pub decision_type: DecisionType,

    /// Confidence score (0.0 - 1.0)
    pub confidence: f64,

    /// Optional reason code
    pub reason_code: Option<String>,

    /// Raw model output (for internal use)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_output: Option<Vec<f32>>,
}

/// The complete JOLT-Atlas proof structure
///
/// This proof cryptographically demonstrates that a specific model
/// produced a specific output from a specific input.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JoltAtlasProof {
    /// Model commitment binding proof to model version
    pub model_commitment: ModelCommitment,

    /// Input commitment (privacy-preserving)
    pub input_commitment: InputCommitment,

    /// Output commitment
    pub output_commitment: OutputCommitment,

    /// The cryptographic execution proof (JOLT/HyperNova)
    #[serde(with = "base64_serde")]
    pub execution_proof: Vec<u8>,

    /// Proof generation timestamp (Unix seconds)
    pub timestamp: u64,

    /// Proof format version
    pub version: u32,
}

impl JoltAtlasProof {
    /// Serialize proof to bytes
    pub fn to_bytes(&self) -> crate::Result<Vec<u8>> {
        serde_json::to_vec(self).map_err(|e| crate::Error::Serialization(e.to_string()))
    }

    /// Deserialize proof from bytes
    pub fn from_bytes(bytes: &[u8]) -> crate::Result<Self> {
        serde_json::from_slice(bytes).map_err(|e| crate::Error::Serialization(e.to_string()))
    }

    /// Encode proof as base64 for HTTP headers
    pub fn to_base64(&self) -> crate::Result<String> {
        let bytes = self.to_bytes()?;
        Ok(base64::Engine::encode(
            &base64::engine::general_purpose::STANDARD,
            &bytes,
        ))
    }

    /// Decode proof from base64
    pub fn from_base64(encoded: &str) -> crate::Result<Self> {
        let bytes = base64::Engine::decode(&base64::engine::general_purpose::STANDARD, encoded)
            .map_err(|e| crate::Error::Serialization(e.to_string()))?;
        Self::from_bytes(&bytes)
    }

    /// Check if proof is still fresh (not expired)
    pub fn is_fresh(&self, max_age_seconds: u64) -> bool {
        let now = current_timestamp();
        now.saturating_sub(self.timestamp) <= max_age_seconds
    }
}

/// Verification result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationResult {
    /// Whether the proof is valid
    pub valid: bool,

    /// Verified model commitment
    #[serde(with = "hex_array_serde")]
    pub model_commitment: [u8; 32],

    /// Timestamp of verification
    pub verified_at: u64,

    /// Error message if invalid
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl VerificationResult {
    /// Create a valid result
    pub fn valid(model_commitment: [u8; 32]) -> Self {
        Self {
            valid: true,
            model_commitment,
            verified_at: current_timestamp(),
            error: None,
        }
    }

    /// Create an invalid result with error message
    pub fn invalid(error: impl Into<String>) -> Self {
        Self {
            valid: false,
            model_commitment: [0u8; 32],
            verified_at: current_timestamp(),
            error: Some(error.into()),
        }
    }
}

/// Registered model information from Visa registry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisteredModel {
    /// The model commitment
    #[serde(with = "hex_array_serde")]
    pub commitment: [u8; 32],

    /// Agent identifier
    pub agent_id: String,

    /// Registration timestamp
    pub registered_at: u64,

    /// Model version
    pub version: String,

    /// Model name/description
    pub name: Option<String>,

    /// Whether the model is active
    pub active: bool,
}

/// Get current Unix timestamp
pub fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// Serde helper for base64 encoding
mod base64_serde {
    use base64::Engine;
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(bytes: &[u8], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let encoded = base64::engine::general_purpose::STANDARD.encode(bytes);
        serializer.serialize_str(&encoded)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<Vec<u8>, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        base64::engine::general_purpose::STANDARD
            .decode(&s)
            .map_err(serde::de::Error::custom)
    }
}

/// Serde helper for hex encoding fixed arrays
mod hex_array_serde {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(bytes: &[u8; 32], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&hex::encode(bytes))
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<[u8; 32], D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        let bytes = hex::decode(&s).map_err(serde::de::Error::custom)?;
        bytes
            .try_into()
            .map_err(|_| serde::de::Error::custom("invalid length for 32-byte array"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_input_commitment_from_bytes() {
        let data = b"test transaction context";
        let commitment = InputCommitment::from_bytes(data);

        assert_eq!(commitment.schema_version, 1);
        assert!(!commitment.hash_hex().is_empty());
    }

    #[test]
    fn test_input_commitment_deterministic() {
        let data = b"same input";
        let c1 = InputCommitment::from_bytes(data);
        let c2 = InputCommitment::from_bytes(data);

        assert_eq!(c1.hash, c2.hash);
    }

    #[test]
    fn test_decision_type_serialization() {
        let approve = DecisionType::Approve;
        let json = serde_json::to_string(&approve).unwrap();
        assert_eq!(json, "\"approve\"");

        let deny: DecisionType = serde_json::from_str("\"deny\"").unwrap();
        assert_eq!(deny, DecisionType::Deny);
    }

    #[test]
    fn test_verification_result() {
        let valid = VerificationResult::valid([1u8; 32]);
        assert!(valid.valid);
        assert!(valid.error.is_none());

        let invalid = VerificationResult::invalid("test error");
        assert!(!invalid.valid);
        assert_eq!(invalid.error.as_deref(), Some("test error"));
    }
}
